### ISSUE TITLE
Incorrect watson-developer-cloud package in package.json

### ISSUE THREAD

**Issue by splatcollision** [watson-developer-cloud/concept-expansion-nodejs#1]
Hi -

Great sample app, but upon a clone and following the instructions, I was unable to push to a new bluemix app. The reason is that 'watson-developer-cloud-alpha' is specified in the package.json, which is not in the NPM registry.

I solved this locally by simply npm installing the correct module 'watson-developer-cloud' and updating app.js to include this instead of the alpha version.

**Comment by germanattanasio** [comment]
nice catch!

**Comment by germanattanasio** [comment]
fixed in b3968336b984ee222534a0a350cd29c385559196
