### ISSUE TITLE
Additional datasets

### ISSUE THREAD

**Issue by willsr** [watson-developer-cloud/concept-expansion-nodejs#3]
Is there any documentation available on creating additional datasets for concept expansion?

And if so, could it be added to the repo docs?

**Comment by germanattanasio** [comment]
Hi @willsr the only way to create your own corpus is to become a [*Ecosystem Partner*](http://www.ibm.com/smarterplanet/us/en/ibmwatson/ecosystem.html).

Once you do that you will get access to a web application that help you to create your own corpus.
