### ISSUE TITLE
confused by demo app

### ISSUE THREAD

**Issue by hauran** [watson-developer-cloud/concept-expansion-nodejs#5]
once the localhost app is running, what is the endpoint to hit?

in the commit [6e34b742f03dcf90d97febe829faba52459e974d](https://github.com/watson-developer-cloud/concept-expansion-nodejs/tree/6e34b742f03dcf90d97febe829faba52459e974d)

was the views directory removed on purpose?
and the root endpoint was removed as well?
```
app.get('/', function(req, res) {
  res.render('index', req.query);
});
```

**Comment by hauran** [comment]
this commit seems to work great
[d4d55e12e2e8f0c8326ad87fe1a68198ae740173](https://github.com/watson-developer-cloud/concept-expansion-nodejs/tree/d4d55e12e2e8f0c8326ad87fe1a68198ae740173)

**Comment by germanattanasio** [comment]
The index.html file doesn't need a route. that why we don't have a views folder.

Everything is AJAX and you will see 3 endpoints in app.js check those and the javascript in the client side.

**Comment by hauran** [comment]
but where is the index.html file? @germanattanasio

**Comment by germanattanasio** [comment]
you were right. I just pushed the file
